<a href="https://colab.research.google.com/github/hru003/Learning/blob/main/Numpy/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Tutorial

### N-dimensional array

![picture](https://www.tutorialspoint.com/numpy/images/ndarray.jpg)

numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

1-D array

In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [25]:
a = np.array((4,5,6,7))
print(a)

[4 5 6 7]


2-D array

In [2]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


Minimum Dimension

In [3]:
a = np.array([1, 2, 3,4,5], ndmin = 2)
print(a)

[[1 2 3 4 5]]


Dtype

In [4]:
a = np.array([1, 2, 3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


Copy

In [21]:
a = np.array([1, 2, 3, 4])
b = np.array(a, copy=False)
print(a)
print(b)
b[0] = 5
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]
[5 2 3 4]
[5 2 3 4]


In [22]:
a = np.array([1, 2, 3, 4])
b = np.array(a, copy=True)
print(a)
print(b)
b[0] = 5
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[5 2 3 4]


In [23]:
a = np.array([1, 2, 3, 4])
b = np.array(a, copy=True)
print(a)
print(b)
a[0] = 5
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]
[5 2 3 4]
[1 2 3 4]


### Data Types

In [32]:
dt = np.dtype(np.int32)
print(dt)

int32


In [33]:
dt = np.dtype([('age',np.int8)])
print(dt)

[('age', 'i1')]


In [36]:
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)], dtype = dt)
print(a)
print(a['age'])

[(10,) (20,) (30,)]
[10 20 30]


In [37]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')])
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student)
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [38]:
print(a['marks'])

[50. 75.]
