<a href="https://colab.research.google.com/github/hru003/Learning/blob/main/Numpy/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Tutorial

## N-dimensional array

![picture](https://www.tutorialspoint.com/numpy/images/ndarray.jpg)

numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

1-D array

In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


2-D array

In [10]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


Minimum Dimension

In [5]:
a = np.array([1, 2, 3,4,5], ndmin = 2)
print(a)

[[1 2 3 4 5]]


Dtype

In [8]:
a = np.array([1, 2, 3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]
